[package]
name = "embedded-chacha"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20 = { version = "0.9.1", default-features = false }
embedded-io = { version = "0.6.1", default-features = false }
embedded-io-async = { version = "0.6.1", default-features = false }
